# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Carmine Sacco
email: carmine.sacco91@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Software Engineer.
logo: assets/images/logo.png
#[""true" or "false" to indicate whether to provide a download URL]"
show_downloads: "true"
#google_analytics: [Your Google Analytics tracking ID]
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://carminoplata.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  carminoplata

# Source directory
#source: dist
# github configurations check https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
lsi: false #Produce an index for related posts. 
# Disables incremental build ==> builds only posts and pages which are changed
incremental: false
highlighter: rouge

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

exclude:
  - .sass_cache/
  - .jekyll-cache/
  - Gemfile
  - README.md
  - node_modules/
  - assets/css/*.scss
  - webpack/
  - webpack.config.js
  - package-lock.json
  - package.json
  - babel.config.json
  - _posts/

assets:
  source_maps: true
  destination: "/assets"
  compress:
    css: false # dev = false, production = true
    js: false # dev = false, production = true
  gzip: false
  defaults:
    integrity:
      {css,img,js}: false
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  # --
  # Assets you wish to always have compiled.
  #   This can also be combined with raw_precompile which
  #   copies assets without running through the pipeline
  #   making them ultra fast.
  # --
  precompile: []
  raw_precompile: [
    #
  ]
  # --
  # baseurl: whether or not to append site.baseurl
  # destination: the folder you store them in on the CDN.
  # url: the CDN url (fqdn, or w/ identifier).
  # --
  cdn:
    baseurl: false
    destination: false
    url: null
  # --
  # See lib/jekyll/assets/config.rb
  #   for a list of defaults
  # --
  sources:
    - "assets/js"
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
